name: Aks_cluster_infra
on: workflow_dispatch
permissions: 
   id-token: write
   contents: read

jobs: 
  terraform-job:
    name: terraform init plan fmt
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
        
     

        #---------- Authenticate to Azure using OIDC------------
        
        
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # - name: Install Terraform
      #   uses: little-core-labs/install-terraform@v2.0.0
      #   with:
      #     version: 1.9.8    

          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true 
        working-directory: Env/Dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Env/Dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: Env/Dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true  
        working-directory: Env/Dev

  Terraform_apply: 
    name: Terraform Apply
    runs-on:  ubuntu-latest
    needs:  terraform-job
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      # - name: Install Terraform
      #   uses: little-core-labs/install-terraform@v2.0.0
      #   with:
      #     version: 1.9.8

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: Env/Dev    
          
      - name: Terraform Apply
        id: apply
        # if: success()           
        run: terraform apply -auto-approve 
        continue-on-error: true 
        working-directory: Env/Dev
    
